---
apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose --file docker-compose.yml convert -o ./manifests/
    kompose.version: 1.36.0 (HEAD)
  labels:
    io.kompose.service: backend
  name: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: backend
  template:
    metadata:
      annotations:
        kompose.cmd: kompose --file docker-compose.yml convert -o ./manifests/
        kompose.version: 1.36.0 (HEAD)
      labels:
        io.kompose.service: backend
    spec:
      containers:
        - env:
            - name: SPRING_DATASOURCE_PASSWORD
              value: root
            - name: SPRING_DATASOURCE_URL
              value: jdbc:mysql://jp-db:3306/mydatabase
            - name: SPRING_DATASOURCE_USERNAME
              value: root
          image: europe-central2-docker.pkg.dev/argon-fire-467320-j2/jp-images-registry/journey-planner-backend:latest
          name: jp-backend
          ports:
            - containerPort: 8080
              protocol: TCP
      restartPolicy: Always
