---
apiVersion: v1
kind: Service
metadata:
  name: frontend-loadbalancer-service
spec:
  type: LoadBalancer
  selector:
    io.kompose.service: frontend
  ports:
    - port: 80
      targetPort: 3000
