---
name: Build Journey Planner Frontend
on:
  push:
    branches: [master]
  pull_request:
    types: [opened, synchronize, reopened]
env:
  IMAGE_NAME: gcr.io/${{ secrets.GKE_PROJECT_ID }}/journey-planner-backend
  IMAGE_TAG: ${{ github.sha }}
jobs:
  build:
    name: Build and test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4.2.2
        with:
          fetch-depth: 0
      - name: Setup NodeJS
        uses: actions/setup-node@v4
        with:
          node-version: 22.14.0
      - name: Get dependencies
        run: |-
          cd ./frontend
          npm install
      - name: Build and test
        run: |-
          ./scripts/build_backend.sh ${{ env.IMAGE_NAME }} ${{ env.IMAGE_TAG }}
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3.11.1
