---
name: Build Journey Planner Backend
on:
  push:
    branches: [master]
  pull_request:
    types: [opened, synchronize, reopened]
env:
  IMAGE_NAME: gcr.io/${{ secrets.GCP_PROJECT_ID }}/journey-planner-backend
  IMAGE_TAG: ${{ github.sha }}
jobs:
  build:
    name: Build and test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4.2.2
        with:
          fetch-depth: 0
      - name: Set up JDK 21
        uses: actions/setup-java@v4.7.1
        with:
          java-version: 21
          distribution: temurin
      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4
      - name: Cache Gradle packages
        uses: actions/cache@v4.2.3
        with:
          path: ~/.gradle/caches
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle') }}
          restore-keys: ${{ runner.os }}-gradle
      - name: Build and test
        env:
          GEO_API_KEY: ${{ secrets.GEO_API_KEY }}
        run: |-
          ./scripts/build_backend.sh ${{ env.IMAGE_NAME }} ${{ env.IMAGE_TAG }}
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3.11.1
      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v2.1.11
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}
      - name: Configure Docker to use gcloud as a credential helper
        run: |-
          gcloud auth configure-docker '${{ secrets.GCP_ARTIFACT_REGISTRY }}'
      - name: Push Docker image to Google Container Registry
        run: |-
          docker push "${{ env.IMAGE_NAME }}:${{ env.IMAGE_TAG }}"
